/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   ft_run.h                                           :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: nirugger <nirugger@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2026/05/18 12:02:32 by nirugger          #+#    #+#             */
/*   Updated: 2026/05/18 17:55:56 by nirugger         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef FT_RUN_H
# define FT_RUN_H

# define RED "\033[0;31m"
# define GREEN "\033[0;32m"
# define YELLOW "\033[0;33m"
# define BLUE "\033[0;34m"
# define MAGENTA "\033[0;35m"
# define CYAN "\033[0;36m"
# define RESET "\033[0m"

# define DNG "d[-_o]q"
# define CMP "p[○┬●]q"
# define DBG "d[0m0]b"
# define RFC "q[¤Q¤]p"
# define BRN "b[✖:✖]d"

# define S00 "nirugger"
# define S01 "aflorea"
# define S02 "fbertozz"
# define S03 "tvanni"
# define S04 "lesbrocc"
# define S05 "alfiorav"
# define S06 "eturini"
# define S07 "sadell-e"
# define S08 "lmongili"
# define S09 "dioppolo"
# define S10 "sfabi"
# define S11 "fracerba"
# define S12 "edraccan"
# define S13 "sfiorini"
# define S14 "alerusso"
# define S15 "pmarani"
# define S16 "fbinchi"
# define S17 "grappo"
# define S18 "cavivian"
# define S19 "lscarpul"
# define S20 "mcecchel"
# define S21 "lmenoni"
# define S22 "giomastr"
# define S23 "gnicolo"
# define S24 "miricci"
# define S25 "francema"
# define S26 "adegl-in"
# define S27 "topiana-"
# define S28 "mapascal"
# define S29 "marmoret"
# define S30 "dmandric"
# define S31 "yel-moha"
# define S32 "ggabor"
# define S33 "mbrighi"
# define S34 "lamici"
# define S35 "marbus"
# define S36 "ginobile"
# define S37 "dbianchi"
# define S38 "pasbarba"
# define S39 "aaamiri"
# define S40 "gifanell"
# define S41 "riccvern"
# define S42 "lavverat"
# define S43 "mdell-os"
# define S44 "sdell-er"
# define S45 "cpopolan"
# define S46 "acentron"
# define S47 "chrilomb"
# define S48 "gcerrete"
# define S49 "sarpolse"
# define S50 "mohfalla"
# define S51 "amancheg"
# define S52 "tcostant"
# define S53 "fdonati"
# define S54 "edingwiz"
# define S55 "icoman"
# define S56 "sel-khao"
# define S57 "gumagni"
# define S58 "flavides"
# define S59 "pipriolo"
// # define S60 ""
// # define S61 ""
// # define S62 ""
// # define S63 ""
// # define S64 ""
// # define S65 ""
// # define S66 ""
// # define S67 ""
// # define S68 ""
// # define S69 ""
// # define S70 ""
// # define S71 ""
// # define S72 ""
// # define S73 ""
// # define S74 ""
// # define S75 ""
// # define S76 ""
// # define S77 ""
// # define S78 ""
// # define S79 ""

#endif